apiVersion: v1
kind: Service
metadata:
  name: orders-api
  namespace: ecommerce-platform
  labels:
    app: orders-api
spec:
  type: NodePort  # Accesible externamente para pruebas
  selector:
    app: orders-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
    # nodePort se asignará automáticamente en el rango 30000-32767
