apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: orders-api-hpa
  namespace: ecommerce-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders-api
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
